### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by vania-pooh** [allure-framework/allure-report-builder#3]
Allure CLI and respective tools are unusable when working behind proxy. Need to provide API allowing to specify proxy settings. When done will be added to CLI.

http://sonatype.github.io/sonatype-aether/apidocs/org/sonatype/aether/repository/Proxy.html
http://download.eclipse.org/aether/aether-core/0.9.0.M2/apidocs/org/eclipse/aether/repository/class-use/Proxy.html

**Comment by hchiao** [comment]
Hi Vania,

Can you please give me an example of how to run allure behind a PROXY?  I've tried setting up the setting.xml in .m2 but maven doesn't seem to be picking it up.  Would there be a command line argument in allure to just pass in the information?  In maven, the command is mvn install -DproxySet=true -DproxyHost=YOUR_PROXY_HOST -DproxyPort=YOUR_PROXY_PORT.

Cheers,
Mike

**Comment by vania-pooh** [comment]
@hchiao you need to add the following to **~/.m2/settings.xml**:

``` xml
  <proxies>
   <proxy>
      <id>example-proxy</id>
      <active>true</active>
      <protocol>http</protocol>
      <host>proxy.example.com</host>
      <port>8080</port>
      <username>proxyuser</username>
      <password>somepassword</password>
      <nonProxyHosts>www.google.com|*.example.com</nonProxyHosts>
    </proxy>
  </proxies>
```

The most problematic case is when trying to use this with Windows because I don't know where user directory (~) is.

**Comment by hchiao** [comment]
@vania-pooh I'm running on ubuntu.  I've installed apache-maven-3.3.3 and I've exported the relevant M2_HOME, M2, MAVEN_OPTS and PATH=$M2:$PATH.  

I've also set the settings.xml in the $M2_HOME/conf/settings.xml and also ~.m2/settings.xml.  Maven is working correctly behind the proxy now, however allure-cli is still giving me java.lang.NullPointerException.  
Any ideas?

I've got the allure-junit-example working, currently just copying the xml files produced via pytest adapter, to the project and it works.

**Comment by vania-pooh** [comment]
We'll release a new version of CLI supporting offline mode during next days, so stay tuned.

**Comment by hchiao** [comment]
@vania-pooh Thanks!!! Will be eagerly anticipating.

**Comment by meesala9** [comment]
@Vania-pooh: Thanks for the information. Do we have any update on the new version release date. 
I am trying to generate the reports from the virtual machine and getting the same error null pointer execeptions. 

Eagerly waiting for the new version release. Thank you.

**Comment by vania-pooh** [comment]
@meesala9 you can start playing with this one. https://github.com/allure-framework/allure-cli/releases/tag/allure-cli-2.4 It already supports the stuff called bundles - you download a bundle with Java code who knows how to generate a report of concrete version. You can download the bundle manually and place it to offline machine via copy-paste and CLI will still work. Please ask if you have any questions.

**Comment by meesala9** [comment]
@vania-pooh: When I tried to use the <b>Allure upgrade</b> command for the latest version to download the bundles, I got the below error:

Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
Exception in thread "main" retrofit.RetrofitError: connect timed out
        at retrofit.RetrofitError.networkError(RetrofitError.java:27)
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
        at com.sun.proxy.$Proxy14.getMetadata(Unknown Source)
        at ru.yandex.qatools.allure.command.BundleUpgrade.runUnsafe(BundleUpgrad
e.java:27)
        at ru.yandex.qatools.allure.command.AbstractCommand.run(AbstractCommand.
java:66)
        at ru.yandex.qatools.allure.AllureCLI.main(AllureCLI.java:55)
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.ja
va:345)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocket
Impl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java
:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:656)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewH
ttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConn
ection.java:1104)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConne
ction.java:998)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect
(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLCo
nnection.java:1512)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLCon
nection.java:1440)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480
)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Htt
psURLConnectionImpl.java:338)
        at retrofit.client.UrlConnectionClient.readResponse(UrlConnectionClient.
java:73)
        at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:
38)
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
        ... 5 more

Can you guide, how to download the bundles manually and add it to the allure-cli.
Thank you.

**Comment by vania-pooh** [comment]
@meesala9: please do the following:
1) Download jar file [here](http://mvnrepository.com/artifact/ru.yandex.qatools.allure/allure-bundle/1.4.17)
2) Create the following directories and place jar file:

``` bash
vania-pooh:~$ ls ~/.allure/bundles/1.4.17/
allure-bundle.jar
```

Then do:

``` bash
$ allure switch 1.4.17
```

Then you should be able to generate report offline.

**Comment by hchiao** [comment]
@vania-pooh I tried your above steps but I'm getting the error 
←[0;31mERROR: ←[mCould not switch to version "1.4.17": the version is not installed.%nThe installed versions: [].

**Comment by vania-pooh** [comment]
@hchiao I forgot about the second step. Create the following file and try again:

``` bash
vania-pooh:~$ cat ~/.allure/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<config>
    <reportPath>allure-report</reportPath>
    <currentVersion>1.4.17</currentVersion>
    <previousVersion>1.4.17</previousVersion>
    <installedVersions>
        <version>1.4.17</version>
    </installedVersions>
</config>
```

**Comment by meesala9** [comment]
@vania-pooh I tried with the following steps, but not able to switch to the bundle

Below are the steps performed on windows machine:
1. Downloaded the Jar and added to my allure-cli folder
2. Placed the XML file in the allure-cli folder
3. Opened the cmd prompt:
      a. Navigated to the allure/bin folder
      b. used the command "allure switch 1.4.17"

Following is observation:
C:\Users\lmeesalx\Desktop\allure\bin>allure switch 1.4.17
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
←[0;31mERROR: ←[mCould not switch to version "1.4.17": the version is not installed.%nThe installed versions: [].

Can you please guide me if I am missing any where!

**Comment by vania-pooh** [comment]
Summon @baev.

**Comment by meesala9** [comment]
Hello @baev,
Can you help me in generating the reports in proxy.
