### ISSUE TITLE
XSLT error while generating allure report

### ISSUE THREAD

**Issue by asolntsev** [allure-framework/allure-report-builder#9]
Getting the following error: 

```java
  XTDE0410: An attribute node (version) cannot be created after the children of the containing element
  at xsl:call-template name="copy-all-without-namespace" (#192)
  at xsl:apply-templates (#27)
     processing /alr:allure-test-run/test-suites[1]/test-suite[1]/@version
```

Archive with build artifacts: https://www.dropbox.com/s/vwsajj1n56md8zm/target.zip?dl=0

Full stack trace:

```java
Downloaded: http://repo.maven.apache.org/maven2/ru/yandex/qatools/allure/allure-report-data/1.3.9/allure-report-data-1.3.9.jar (46 KB at 901.8 KB/sec)
                                 
Downloaded: http://repo.maven.apache.org/maven2/ru/yandex/qatools/properties/properties-loader/1.4/properties-loader-1.4.jar (15 KB at 293.6 KB/sec)
                                 
Downloaded: http://repo.maven.apache.org/maven2/ru/yandex/qatools/allure/allure-model/1.3.9/allure-model-1.3.9.jar (28 KB at 489.5 KB/sec)
Error on line 196 
  XTDE0410: An attribute node (version) cannot be created after the children of the containing element
  at xsl:call-template name="copy-all-without-namespace" (#192)
  at xsl:apply-templates (#27)
     processing /alr:allure-test-run/test-suites[1]/test-suite[1]/@version
  at xsl:apply-templates (#197)
     processing /alr:allure-test-run/test-suites[1]/test-suite[1]
  at xsl:call-template name="copy-all-without-namespace" (#192)
  at xsl:apply-templates (#14)
     processing /alr:allure-test-run/test-suites[1]
  in built-in template rule
[ERROR] Can't generate allure report data
ru.yandex.qatools.allure.report.AllureReportBuilderException: java.lang.reflect.InvocationTargetException
	at ru.yandex.qatools.allure.report.AllureReportBuilder.processResults(AllureReportBuilder.java:135)
	at ru.yandex.qatools.allure.report.AllureReportMojo.executeReport(AllureReportMojo.java:100)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:196)
	at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:219)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:319)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:135)
	at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:175)
	at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:138)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at ru.yandex.qatools.allure.report.AllureReportBuilder.processResults(AllureReportBuilder.java:133)
	... 28 more
Caused by: ru.yandex.qatools.allure.data.ReportGenerationException: net.sf.saxon.event.NoOpenStartTagException: An attribute node (version) cannot be created after the children of the containing element
	at ru.yandex.qatools.allure.data.utils.XslTransformationUtils.applyTransformation(XslTransformationUtils.java:55)
	at ru.yandex.qatools.allure.data.utils.XslTransformationUtils.applyTransformation(XslTransformationUtils.java:44)
	at ru.yandex.qatools.allure.data.utils.XslTransformationUtils.applyTransformation(XslTransformationUtils.java:35)
	at ru.yandex.qatools.allure.data.utils.XslTransformationUtils.applyTransformations(XslTransformationUtils.java:29)
	at ru.yandex.qatools.allure.data.TestSuiteFiles.generateTestRun(TestSuiteFiles.java:50)
	at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:39)
	... 33 more
Caused by: net.sf.saxon.event.NoOpenStartTagException: An attribute node (version) cannot be created after the children of the containing element
	at net.sf.saxon.event.NoOpenStartTagException.makeNoOpenStartTagException(NoOpenStartTagException.java:49)
	at net.sf.saxon.event.ComplexContentOutputter.attribute(ComplexContentOutputter.java:296)
	at net.sf.saxon.instruct.CopyOf.copyAttribute(CopyOf.java:572)
	at net.sf.saxon.instruct.Copy.processLeavingTail(Copy.java:221)
	at net.sf.saxon.instruct.Template.expand(Template.java:220)
	at net.sf.saxon.instruct.CallTemplate$CallTemplatePackage.processLeavingTail(CallTemplate.java:440)
	at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:317)
	at net.sf.saxon.instruct.ApplyTemplates.apply(ApplyTemplates.java:210)
	at net.sf.saxon.instruct.ApplyTemplates.processLeavingTail(ApplyTemplates.java:174)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:556)
	at net.sf.saxon.instruct.Instruction.process(Instruction.java:93)
	at net.sf.saxon.instruct.ElementCreator.processLeavingTail(ElementCreator.java:296)
	at net.sf.saxon.instruct.Template.applyLeavingTail(Template.java:203)
	at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:345)
	at net.sf.saxon.instruct.ApplyTemplates.apply(ApplyTemplates.java:210)
	at net.sf.saxon.instruct.ApplyTemplates.process(ApplyTemplates.java:170)
	at net.sf.saxon.instruct.ElementCreator.processLeavingTail(ElementCreator.java:296)
	at net.sf.saxon.instruct.Copy.processLeavingTail(Copy.java:217)
	at net.sf.saxon.instruct.Template.expand(Template.java:220)
	at net.sf.saxon.instruct.CallTemplate$CallTemplatePackage.processLeavingTail(CallTemplate.java:440)
	at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:317)
	at net.sf.saxon.instruct.ApplyTemplates.apply(ApplyTemplates.java:210)
	at net.sf.saxon.instruct.ApplyTemplates.processLeavingTail(ApplyTemplates.java:174)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:556)
	at net.sf.saxon.instruct.Instruction.process(Instruction.java:93)
	at net.sf.saxon.instruct.ElementCreator.processLeavingTail(ElementCreator.java:296)
	at net.sf.saxon.instruct.Template.applyLeavingTail(Template.java:203)
	at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:345)
	at net.sf.saxon.instruct.ApplyTemplates.defaultAction(ApplyTemplates.java:378)
	at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:333)
	at net.sf.saxon.Controller.transformDocument(Controller.java:1807)
	at net.sf.saxon.Controller.transform(Controller.java:1621)
	at ru.yandex.qatools.allure.data.utils.XslTransformationUtils.applyTransformation(XslTransformationUtils.java:52)
	... 38 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.896 s
[INFO] Finished at: 2015-02-24T18:24:15+02:00
[INFO] Final Memory: 18M/223M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project selenide-allure-junit: Error during page generation: Error rendering Maven report: Can't generate allure report data: java.lang.reflect.InvocationTargetException: net.sf.saxon.event.NoOpenStartTagException: An attribute node (version) cannot be created after the children of the containing element -> [Help 1]
```

**Comment by baev** [comment]
You should generate report with the same version

**Comment by asolntsev** [comment]
@baev I don't understand. Version of what?
Sure I am running tests and generating report with the same maven version (3.2.1).

I have found that the reason. I didn't declare property "allure.version" in my pom.xml. Without this property report generation fails.

Adding this line resolves the problem: `<allure.version>1.4.3</allure.version>`

I believe this is a bug. The property must not be required.

**Comment by baev** [comment]
When you generate report you should specify report version. By default it is 1.3.9. When you use maven plugin you can specify report version using property *allure.version* or via *reportVersion* configuration parameter.

BTW Right now we are working on new migration system that can help to solve you your problem

**Comment by asolntsev** [comment]
My point is, that report generation could either use default version, or detect current version of allure.jar (that is actually working right now). Whatever - it can be done automatically. Why bother user about such details?

**Comment by baev** [comment]
My answer is - historically

As i say before we working on it)

**Comment by baev** [comment]
Anyway thanks for suggestion

**Comment by eroshenkoam** [comment]
#10 close
